### PR TITLE
Improve BOM a bit, optimise for low MOQ

### PR DESCRIPTION
**Pull request by kasbah**
Hey, I fixed the BOM a bit and optimised for lower minimum order quantities.

That is a lot of headers! I didn't realise that you would select each one like this when you asked. I think it would make sense to pick out a large single-row break away header that can cover all of these. Just one item on the BOM. What do you think?

### CODE REVIEW

**Comment by yaqwsx** [comment]
Hi, thank you for the small tweaks! However, the BOM generated by Eagle and I don't want to make manual  modifications. The schematics is what drives everything and with hand modification to BOM, it is easy to get out-of-sync. Therefore I have adopted your changes to the schematic and I will commit these changes to the repository.

This is also the reason why I asked you about the pin headers - if I have an automatically generated BOM I can have only one component per schematic component. No merging, splitting, etc.

**Comment by kasbah** [comment]
Ah, I didn't realise it was completely generated from the schematic. Mind sharing the ULP so I can add it to [1-click BOM output scripts](https://github.com/monostable/1clickBOM/tree/master/output_scripts/)?  Would be really cool if there was something to put the info back into the schematic like [KiField](https://github.com/xesscorp/KiField) can for KiCAD. 

Maybe you could just attach a large single row header to the largest one and leave the rest off? I know it's not perfect but the cart with all these one-off headers is never going to make sense to buy for _anyone_ I think.

**Comment by yaqwsx** [comment]
I use standard bom.ulp, which produces CSV files. Then I replace "\"" -> "" and ";" -> "\t" by simple sed script  to get TSV file.

I really miss KiField in Eagle. Managing attributes in Eagle is hell. I used https://github.com/xesscorp/Eagle_PCB/blob/master/xess_ulp/attrib-copy.ulp to make it a little bit easier (but still no win).

**Comment by kasbah** [comment]
What do you want to do about the headers?

**Comment by yaqwsx** [comment]
I am thinking about discarding them from the BOM. As you stated - they aren't useful to anyone. Maybe a section in readme, saying what is and what is not in BOM, is the best option. What do you think?

**Comment by yaqwsx** [comment]
Everything is fine now, so closing.

**Pull request closed without merging**
